aws:
  accessKeyId: ${AWS_ACCESS_KEY_ID:5aa96de161d84c1c882ed61915c2b757}
  secretAccessKey: ${AWS_SECRET_ACCESS_KEY:5ea158f52c424c759386f94342e23006}
  region: ${AWS_REGION:eu-west-1}
  sqs:
    uri: ${SQS_URI:http://localhost:9324}

server:
  port: 8084

spring:
  data:
    mongodb:
      port: 27017
      #port: 27020